# FreshCart – Application Properties
server.port=8080

# Disable Spring MVC auto-config (we use raw Servlets/JSP)
spring.application.name=grocery-management
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
